folder/project/app1/urls.py
from django.urls import path

from . import views
urlpatterns =[
    path('', views.home, name='home'),
    path('create/', views.create_view, name='create'),
    path('lists/', views.list_view, name='lists'),
    path('<id>/', views.detail_view, ),
    path('<id>/update', views.update_view ),
    path('<id>/delete', views.delete_view,name='delete'),
]

folder/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from app1 import views as app1_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', user_views.dashboard, name='dashboard'),
    path('register/', user_views.register, name='register'),

    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),  # cls based view
    path('profile/', user_views.profile, name='profile'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),

    path('', include('app1.urls')),

]

folder/project/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

]


folder/project/app1/models.py
from django.db import models

# Create your models here.


class blog(models.Model):
    title=models.CharField(max_length=100)
    desc = models.CharField(max_length=100)

    def __str__(self):
        return self.title




folder/project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


CHOICE_GENDER = [(1, 'Male'), (2, 'Female')]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.IntegerField(choices=CHOICE_GENDER, default='1')
    image = models.ImageField(default='default.jpg', upload_to='media')

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)




folder/project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .models import Profile, CHOICE_GENDER


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    CHOICE_GENDER = ((1, 'Male'), (2, 'Female'))
    gender = forms.ChoiceField(required=True, widget=forms.RadioSelect(attrs={"required": "required"}),
                               choices=CHOICE_GENDER)

    class Meta:
        model = User
        fields = ('username', 'email', 'gender', 'password1', 'password2',)

    def save(self, commit=True):
        user = super().save(commit=False)

        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.gender = self.cleaned_data['gender']

        if commit:
            user.save()
        return user


"""
for "Creating___________Custom Fields__________ with registration form "
"""


class ProfileFrom(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('gender', 'image')


"""
___________________________________________________for________Updating Profile FORM______________
"""


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email')


class ProfileUpdateForm(forms.ModelForm):
    CHOICE_GENDER = ((1, 'Male'), (2, 'Female'))
    gender = forms.ChoiceField(required=True, widget=forms.RadioSelect(), choices=CHOICE_GENDER)

    class Meta:
        model = Profile
        fields = ['gender', 'image']


folder/project/users/views.py
from django.shortcuts import render, HttpResponse, Http404, get_object_or_404, redirect
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, ProfileFrom
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


"""
______________________Dashboard________________________
"""

def dashboard(request):
    if request.user.is_authenticated:
        return render(request, 'users/dashboard.html', {'name': request.user.username})
    else:
        pass
    return render(request, 'users/dashboard.html')


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        profile_From = ProfileFrom(request.POST)

        if form.is_valid() and profile_From.is_valid():
            user = form.save()

            profile = profile_From.save(commit=False)
            profile.user = user
            profile.save()
            group = Group.objects.get(name='Editor') #here
            user.groups.add(group)
            messages.success(request, 'Your account has been  created. You can Log In')
            return redirect('login')

    else:
        form = UserRegisterForm()
        profile_From = ProfileFrom()
    return render(request, 'users/register.html', {'form': form, ' profile_From':  profile_From})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()

            messages.success(request, 'Your account has been  Updated..!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'users/profile.html', context)


"""
______________________Logout________________________
"""


def logout_view(request):
    logout(request)


folder/project/users/templates/users/dashboard.html
{% extends "app1/base.html"%}
{% block content %}

<div class="content-section">
        Welcome {{ name }}

    {% if perms.app1.delete_blog %}
        <input type="button" value="Delete"><br>
    {% else %}
        <h3>No permission given </h3>
    {% endif %}

    {% if perms.app1.add_blog %}
        <input type="button" value="Add"><br>
    {% else %}
        <h3>No permission given </h3>
    {% endif %}

   </div>
{% endblock %}

folder/project/users/templates/users/login.html
{% extends "app1/base.html"%}
{% block content %}

<div class="content-section col-md-6 mb-0">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group ">
                <legend class="border-bottom mb-4">Log In</legend>

                <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form}}
                      </div>
                </div>

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
       <div class="border-top pt-3">
        <small class="text-muted">
            Need  An Account?<a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
        </small>
       </div>
   </div>

{% endblock %}

folder/project/users/templates/users/logout.html
{% extends "app1/base.html"%}
{% block content %}
       <h2>You have been Logged Out</h2>
       <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}">Log In Again</a>
            </small>
       </div>
{% endblock %}




folder/project/users/templates/users/password_reset.html
{% extends "app1/base.html"%}
{% block content %}

<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Rest</button>
            </div>
        </form>
   </div>
{% endblock %}

folder/project/users/templates/users/profile.html
{% extends "app1/base.html"%}
{% block content %}

    <div class="content-section col-md-6 mb-0">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Profile Info </legend>

                {{ u_form }}
                {{ p_form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock %}


folder/project/users/templates/users/register.html
{% extends "app1/base.html"%}
{% block content %}

   <div class="content-section col-md-6 mb-0">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register</legend>

                {{ form }}

            </fieldset>

            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
       <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account?<a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
       </div>
   </div>
{% endblock %}


